### ISSUE TITLE
Issue working with large codespace

### ISSUE THREAD

**Issue by mubarekmuhiyie** [bradgarropy/plop-helper-includes#1]
The helper doesn't effectively function for large codespaces when it is called on multiple places within a component with many lines of code. 
Return the error:  ✖  ++ Cannot read properties of undefined (reading 'replace')

**Comment by bradgarropy** [comment]
Do you have a reproduction somewhere that I could take a look at? Or a stack trace?

This codebase doesn't include the word `replace` at all, so I'd need more information to see where it's coming from.

**Comment by mubarekmuhiyie** [comment]
I believe the error(replace of undefined) is thrown by plop built in error handler when it fails to interpret the code when your {{#includes}} is called many times in a template.
Let me include an example code snippet below.

templateFile:

export default interface {{pascalCase feature}} {
    id?: string;
    
    {{#includes fields "code"}}
    code: string;
    {{/includes}}

    {{#includes fields "name"}}
    name: MultiLanguage;
    {{/includes}}

    {{#includes fields "description"}}
    description: MultiLanguage;
    {{/includes}}

    {{#includes fields "dropdown"}}
    {{camelCase feature}}Type: string;
    {{/includes}}

    {{#includes fields "checkbox"}}
    isActive?: boolean;
    {{/includes}}
    
    deletedAt?: string;
}

"fields": ["name", "code", "description", "dropdown", "checkbox"]

Running the generator on this template results in the above error. Can you run this and tell me if you encounter any issues.

**Comment by bradgarropy** [comment]
@mubarekmuhiyie Do you have a link to the repository that I could check out? Or the full contents of the `plopfile`?

**Comment by mubarekmuhiyie** [comment]
I guess the problem was your includes helper iterates through the array and has no way of accessing a data passed to it from an attribute indexed as a parent and not as part of the array( the "feature" variable )in my case.
The JSON is structured in such a way: 
{
 "feature": "featureName",
 "fields": ["name", "code", "description", "dropdown", "checkbox"]
}
As includes iterates through the array it has no way of getting the value given by the feature attribute. I solved the issue by using the #with context switcher of handlebars.

**Comment by bradgarropy** [comment]
Ah yes, that makes sense! This helper only works with array values and not objects. I'm going to go ahead and close this issue then!
